### ISSUE TITLE
ios8.1

### ISSUE THREAD

**Issue by evolut1on** [iSECPartners/ios-ssl-kill-switch#13]
Hi nabla :)

Another year, another iOS :) . Do you think you have the time to update the built to support ios 8.x ?

Cheers!

**Comment by upbit** [comment]
Just build form master and test, it's already support iOS 8.1.

Here is deb: [com.isecpartners.nabla.sslkillswitch_v0.61-iOS_8.1.deb](http://blog.imaou.com/SSLKillSwitch/com.isecpartners.nabla.sslkillswitch_v0.61-iOS_8.1.deb)
Tested on **iOS8.1(12B411)** / iPhone4S ( #12 )

**Comment by mr-gosh** [comment]
works fine - but where is the global button - do I have to activate it app by app?
would be awesome to have the global function back to be able to deactivate certificate validation on all new installed apps?

**Comment by mr-gosh** [comment]
any update on this topic?

**Comment by mr-gosh** [comment]
did someone test this on iOS 8.4

**Comment by majinmartin93** [comment]
It doesnt work on iOS 8.2 :(

**Comment by nabla-c0d3** [comment]
In about a month, I will release a new tool with various improvements here: https://github.com/nabla-c0d3/ios-ssl-kill-switch2

**Comment by majinmartin93** [comment]
that's great thanks, if it's not much trouble to adapt the current version out for 8.2 that'd be great, if you have a bitcoin address i'll leave u 10$ as a thank you :)

**Comment by jalsco** [comment]
Thank you, please make it run on ios 8.4 as soon as you can.. Either the old version updated, or the new ios-ssl-kill-switch2 . I will also leave a BTC tip when the software is ready :)

**Comment by jalsco** [comment]
On ios8.4 runnung ver 0.6-1 gives this: 
![etqykvwm](https://cloud.githubusercontent.com/assets/7985459/8632635/80300770-27e7-11e5-9a0b-38b874ebc0bc.png)

**Comment by nabla-c0d3** [comment]
I just released a "beta" version here: https://github.com/nabla-c0d3/ios-ssl-kill-switch2/releases/tag/0.7
I tried it on a few Apps on iOS 8.4 and it worked fine; make sure you uninstall any previous version first.

**Comment by majinmartin93** [comment]
Cant check right now, should be good for 8.2 as well? Otherwise i'll see if i can upgrade 😊
Whats your bitcoin address?

**Comment by nabla-c0d3** [comment]
Haha don't worry about my bitcoin address - yes it should work on 8.2 but you should probably upgrade to 8.4 while you still can. Once Apple stops signing 8.4 you will be stuck on 8.2...

**Comment by jalsco** [comment]
Thanks 4 trying, but... (on ios 8.4) I uninstalled old version, then installed your new deb, then ran icleaner to clear all caches etc, then a full reboot.. but still problem is still there: 
![image1](https://cloud.githubusercontent.com/assets/7985459/8633001/3ae192ea-27f8-11e5-9953-15d0778b7f68.jpg)

**Comment by nabla-c0d3** [comment]
Did you enable the tweak in the device's Settings?

**Comment by majinmartin93** [comment]
maybe i'm retarded but:
i upgraded to 8.4, installed killswitch, installed burp certificate, put my pc ip as proxy, but i tried with like twitter to check not nothing? am i missing a step or something? i see only the normal stuff i could have seen with even a normal iphone.

**Comment by jalsco** [comment]
Thanks for the tip. I had not enabled it, but now have. Still some problems . See the messages below. The app I am trying to get running is called "VendRegister" it is free from app store, search for "Register".  
![pic1](https://cloud.githubusercontent.com/assets/7985459/8635886/b5628288-2882-11e5-8c56-1bdf182ef252.jpg)

And these : 

![pic2](https://cloud.githubusercontent.com/assets/7985459/8635888/c0480074-2882-11e5-851b-8937691226bd.jpg)

**Comment by mr-gosh** [comment]
installation works fine - but in ios 8.4 i cant install apps during activated MitM - without MitM it works fine... so it seems there is something missing...
Tested on an iPhone and an iPad

**Comment by nabla-c0d3** [comment]
@mr-gosh If you're trying to mitm the App Store it takes more work; some ideas here: https://nabla-c0d3.github.io/blog/2013/08/20/intercepting-the-app-stores-traffic-on-ios/

@jalsco VendRegister crashes instantly. I think it detects that the device is jailbroken and won't run.

I just tried on some Apps and ssl kill switch 2 works fine. Good luck...

**Comment by jalsco** [comment]
I included the message (above) from VendRegister. It shows "SecTrustEvaluate [leaf AnchorTrusted]" , after trying to connect to VendHq servers, then it exits voluntarily. It continues running in background, just won't come to foreground (without connection to their server). It is not typical action of JB detection, usually is "not run at all, and stop running completely". Why the SecTrustEvaluate message if not a certificate problem ??

**Comment by hkclbb** [comment]
able to work with 8.1? i am not able to upgrade to 8.4 now :'(
seems work fine with App Store, but not work with "Apple Store" app

**Comment by nabla-c0d3** [comment]
try https://github.com/nabla-c0d3/ios-ssl-kill-switch2/releases/tag/0.7 - it should work
